apiVersion: v1
kind: Service
metadata:
  name: balance-db
spec:
  selector:
    app: balance-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: balance-db
  labels:
    app: balance-db
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: balance-db
      version: v1
  template:
    metadata:
      labels:
        app: balance-db
        version: v1
    spec:
      containers:
      - name: balance-db
        image: merpay-ms-dev/balance-db:0.1
        ports:
        - containerPort: 3306
